# Generated by Django 3.1.3 on 2020-11-24 14:05

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20201124_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 24, 14, 5, 52, 769054, tzinfo=utc), verbose_name='date joined'),
        ),
    ]
