# Generated by Django 3.1.5 on 2021-02-14 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm', '0002_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=140, verbose_name='First name')),
                ('last_name', models.CharField(max_length=140, verbose_name='Last name')),
                ('phone', models.IntegerField(max_length=10, verbose_name="Customer's phone number")),
                ('email', models.EmailField(max_length=254, verbose_name="Customer's email")),
                ('date_added', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
