# Generated by Django 3.1.5 on 2021-01-24 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0010_auto_20210124_0736'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='company',
            new_name='companies',
        ),
    ]
