name: Django CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install Dependencies
      VaultVulp/action-pipenv@v2.0.1
      with:
        command: install # Install all dependencies
    
    - name: Run Tests
      run: |
        pipenv shell
        python manage.py test
      env:
        SECRET_KEY: TEST_SECRET_KEY
